[package]
name = "thimble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.11"
html-escape = "0.2.13"
tiny_http = "0.12.0"
